config/routes.rb
Rails.application.routes.draw do

  get 'follows/index'

  get 'follows/show'

  get 'users/index'

  get 'users/show'

  devise_for :brands
  devise_for :users
  resources :locations
  resources :designers
  resources :articles
  resources :notifications

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'pages#signup'
  get 'login' => 'pages#login'
  get ':name' =>'brands#show', as: 'brand'
  get ':id' =>'users#show', as: 'id'

  #'brands/show'
  get 'brands/index'

  resources :brands do
    member  do
      get :follow
      get :unfollow
    end
    collection {post :search, to: 'brands#index'}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :brand


  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => 'missing.png'
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/brand.rb
class Brand < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :articles
   has_many :designers
   has_many :locations
   has_many :notifications
   validates_uniqueness_of :name

    acts_as_followable


  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => 'missing.png'
  validates_attachment :logo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/designer.rb
class Designer < ApplicationRecord

  belongs_to :brand
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
belongs_to :brand
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :brand

  default_scope { order("created_at DESC")}

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_follower
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

def index
    @q = Brand.ransack(params[:q])
    @brands = @q.result(distinct: true)
  end

  def show
    @brand = Brand.find_by name: params[:name]
  end

  def follow
    @brand = Brand.find(params[:id])
      current_user.follow(@brand)
      redirect_to :back
end

def unfollow
  @brand = Brand.find(params[:id])
      current_user.stop_following(@brand)
      redirect_to :back
end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]
  before_action :correct_brand, only: [:edit, :update,:destroy]
  before_action :authenticate_brand!, except: [:index, :show]

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
  end

  # GET /designers/new
  def new
    @designer = current_brand.designers.build
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = current_brand.designers.build(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to brand_path(current_brand.name), notice: 'Designer was successfully created.' }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to brand_path(current_brand.name), notice: 'Designer was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to brand_path(current_brand.name), notice: 'Designer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    def correct_brand
      @designer = current_brand.designers.find_by(id: params[:id])
      redirect_to designers_path, notice: 'Not authorized to edit this article' if @designer.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:name, :bio, :avatar)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @brands = Brand.all
    @notifications= Notification.all
  end

  def about
  end

  def signup
  end

  def login
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.find_by(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articleindexes_helper.rb
module ArticleindexesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/designers/_form.html.erb
<%= form_for @designer, html: { multipart: true } do |f| %>
  <% if designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Back', :back%>

app/views/designers/index.html.erb
<div class="center">
<%= link_to 'Brands', brands_index_path %>
</div>

<div id="articles" class="transitions-enabled">
    <% @designers.each do |designer| %>
    <div class="box panel panel-default">
      <%= image_tag designer.avatar.url(:thumb) %>
      <div class="panel-body">
      <strong>Designer: </strong><%= designer.name %></br>
     <strong>Bio: </strong> <%= designer.bio %></br>
      <strong>Brand: </strong><%= designer.brand.name %></br>

        <%= link_to 'Show', designer_path(designer) %></br>
        <% if designer.brand == current_brand %>
        <%= link_to 'Edit', edit_designer_path(designer) %>
        <%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end%>
      </div>
      </div>
      <% end %>
    </div>

app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Back', :back %>

app/views/designers/show.html.erb
<%= image_tag @designer.avatar.url(:medium)%>

<p>
  <strong>Name:</strong>
  <%= @designer.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @designer.bio %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @designer.brand.name %>
</p>


<% if @designer.brand == current_brand %>
<%= link_to 'Edit', edit_designer_path(@designer) %> |
<% end %>
<%= link_to 'Back', :back %>