config/routes.rb
Rails.application.routes.draw do

  get 'follows/index'

  get 'follows/show'

  get 'users/index'

  get 'users/show'

  devise_for :brands
  devise_for :users
  resources :locations
  resources :designers
  resources :articles
  resources :notifications

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'pages#signup'
  get 'login' => 'pages#login'
  get ':name' =>'brands#show', as: 'brand'
  get ':id' =>'users#show', as: 'id'

  #'brands/show'
  get 'brands/index'

  resources :brands do
    member  do
      get :follow
      get :unfollow
    end
    collection {post :search, to: 'brands#index'}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :brand


  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => 'missing.png'
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/brand.rb
class Brand < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :articles
   has_many :designers
   has_many :locations
   has_many :notifications
   validates_uniqueness_of :name

    acts_as_followable


  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => 'missing.png'
  validates_attachment :logo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/designer.rb
class Designer < ApplicationRecord

  belongs_to :brand
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
belongs_to :brand
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :brand

  default_scope { order("created_at DESC")}

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_follower
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @brands = Brand.all
    @notifications= Notification.all
  end

  def about
  end

  def signup
  end

  def login
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.find_by(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_brand_contact.html.erb
<h3>Contact: </h3>
   <strong>Email:</strong> <%= @brand.email %></br>
   <strong>Phone:</strong> <%= @brand.phone %></br>

<%if @brand.url %>
   <strong>Website:</strong>  <%= link_to @brand.url, url_for(@brand.url), target: :_blank%></br>
    <%end%>

app/views/layouts/_brand_location.html.erb
<div class="center">
  <% if brand_signed_in? %>
      <%= link_to  raw('<span class="glyphicon glyphicon-plus"></span>Add Store'), new_location_path %>
  <%end%>
</div>

<% if @brand.locations %>
  <% @brand.locations.each do |location| %>
    <%= location.address %></br>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{location.latitude}%2C#{location.longitude}" %>
    <%= link_to 'Edit', edit_location_path(location) %>
   <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end %>
<%end%>

app/views/layouts/_brand_new.html.erb
<div class="center titles">
    <h3>Nieuwe Merken</h3>
    </div>

    <div id="articles" class="transitions-enabled">
      <% @brands.all.order(created_at: :DESC).each do |brand| %>
          <div class="box panel panel-default">
              <%= link_to image_tag(brand.logo.url(:medium)),brand_path(brand.name) %>
            </div>
         <%end%>
       </div>

app/views/layouts/_brand_pics.html.erb
<div class="center">
  <% if brand_signed_in? %>
      <%= link_to  raw('<span class="glyphicon glyphicon-plus"></span>Add Pic'), new_article_path %>
  <%end%>
</div>

<div id="articles" class="transitions-enabled">
    <% @brand.articles.each do |article| %>
        <div class="box panel panel-default">
            <%= link_to image_tag(article.image.url(:medium)), article %>
            <% if article.brand == current_brand %>
             <div class="panel-body">
              <div class="actions">
                <%= link_to  raw('<span class="glyphicon glyphicon-edit"></span>Edit'), edit_article_path(article) %>
                <%= link_to  raw('<span class="glyphicon glyphicon-trash"></span>Delete'), article, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
              </div>
          <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_brand_popular.html.erb
 <div class="center titles">
    <h3>Populaire Merken</h3>
    </div>

    <div id="brands_popular" class="transitions-enabled">
      <% @brands.all.sort_by(&:followers_count).reverse.each do |brand| %>
          <div class="brandpopularbox panel panel-default">
              <%= link_to image_tag(brand.logo.url(:medium)),brand_path(brand.name) %>
            </div>
         <%end%>
       </div>

app/views/layouts/_brand_posts.html.erb
      <div class="col-xs-4">
      <% @brand.notifications.each do |notification| %>

        <div class="panel panel-default">
        <div class="panel-header">
                <%= image_tag notification.brand.logo.url(:thumb) %>
                </div>
                <div class="panel-body">
              <%if notification.image? %>
                <%= image_tag notification.image %>
              <%end %>
                <h1><%= notification.title %></h1>
                <p>Posted by: <%= notification.brand.name %></p>
                <p><%= notification.description.truncate(120) %></p>
                 <% if brand_signed_in? %>
              <%= link_to 'Edit', edit_notification_path(notification), class: "btn btn-info" %>
              <%= link_to 'Delete', @notification, method: :delete, data: { confirm: "Are you sure?"},class: "btn btn-danger" %>
              <%end%>
              </div>
        </div>

      <% end %>
</div>

app/views/layouts/_city_image.html.erb
 <div id="city">
    <div class="citybox">
  <%=image_tag('antwerpen_pic.jpg') %>
      </div>
    </div>
  </div>

app/views/layouts/_feed.html.erb
<% current_user.all_following.each do |f|%>
  <% f.notifications.each do |notification| %>
      <div class="panel panel-default">
        <div class="panel-header">
          <%=link_to image_tag(notification.brand.logo.url(:thumb)), brand_path(f.name) %>
          </div>
          <div class="panel-body">
              <%if notification.image? %>
                  <%= image_tag notification.image %>
              <%end %>
                <h1><%= notification.title %></h1>
                <p>Posted by: <%= notification.brand.name %> @ <%= notification.created_at %></p>
                <p><%= notification.description.truncate_words(10) %></p>
                <p>Tags: <%= render notification.tags %></p>
                <span><%= notification.get_upvotes.size%></span>
                <% if current_user.voted_up_on? notification %>
                      <%= link_to raw('<span class="glyphicon glyphicon-heart"></span>'), unlike_notification_path(notification), method: :put%>
                <% else%>
                      <%= link_to raw('<span class="glyphicon glyphicon-heart-empty"></span>'), like_notification_path(notification), method: :put%>
                <% end%>
                <%= link_to 'Lees meer', notification %>
        </div>
      </div>
    <% end%>
  <%end%>

app/views/layouts/_followbutton.html.erb
<% if user_signed_in? %>
    <%if current_user.following?(@brand) == true %>
    <%= link_to "Unfollow", unfollow_brand_path(@brand), class: 'btn btn-primary' %>
    <%else %>
    <%= link_to "Follow", follow_brand_path(@brand),class: 'btn btn-primary' %>

  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a><%= link_to "Brandz", root_path, class: 'navbar-brand'%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if brand_signed_in? %>
            <li><%= link_to 'Home', root_path,class: 'nav-link' %></li>
            <li><%= link_to "Log out", destroy_brand_session_path, method: :delete, class: 'nav-link' %></li>
            <li><%= link_to 'Settings', edit_brand_registration_path,class: 'nav-link' %></li>
            <li><%= link_to "Brand It", new_notification_path,class: 'nav-link' %></li>
            <li><%= link_to 'Profile', brand_path(current_brand.name),class: 'nav-link' %></li>
          <% elsif user_signed_in? %>
            <li><%= link_to "Search", brands_index_path,class: 'nav-link' %></li>
            <li><%= link_to "Feed", notifications_path,class: 'nav-link' %></li>
            <li><%= link_to "Following", follows_index_path,class: 'nav-link' %></li>
            <li><%= link_to "Log out user", destroy_user_session_path, method: :delete,class: 'nav-link' %></li>
            <li><%= link_to "Account Settings", edit_user_registration_path,class: 'nav-link' %></li>
            <li><%= link_to "Profile", users_show_path(current_user),class: 'nav-link' %></li>
          <% else %>
            <li><%= link_to "Search", brands_index_path,class: 'nav-link' %></li>
            <li><%= link_to "Sign Up", signup_path,class: 'nav-link' %></li>
        <% end %>


      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_upvote_not.html.erb
    <% current_user.notifications.each do |notification| %>
        <% if current_user.voted_up_on? notification %>
          <%= link_to raw('<span class="glyphicon glyphicon-heart"></span>'), unlike_notification_path(notification), method: :put%>
        <% else%>
          <%= link_to raw('<span class="glyphicon glyphicon-heart-empty"></span>'), like_notification_path(notification), method: :put%>
        <% end%>
        <span><%= notification.get_upvotes.size%></span>
    <% end %>

app/views/layouts/_user_following_brands.html.erb
<h3>Currently following <%= current_user.follows.count%> brands</h3></br>

<div id="articles" class="transitions-enabled">
    <% @brands.each do |brand|%>
    <div class="box panel panel-default">
       <%= link_to image_tag(brand.logo.url(:medium)), brand_path(brand.name)%></br>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_user_following_pic.html.erb
 <% current_user.all_following.each do |f|%>
   <%f.articles.each do |article|%>
          <div class="postbox panel panel-default">
            <div class="panel-header">
                <%= image_tag article.brand.logo.url(:thumb) %>
                </div>
                <div class="panel-body">
                  <%= image_tag article.image.url(:medium) %>
                <p><%= article.brand.name %> posted a new pic</p>
                <p><%= article.description %></p>
                <% if current_user.voted_up_on? article %>
                          <%= link_to raw('<span class="glyphicon glyphicon-heart"></span>'), unlike_article_path(article), method: :put%>
                      <% else%>
                          <%= link_to raw('<span class="glyphicon glyphicon-heart-empty"></span>'), like_article_path(article), method: :put%>
                      <% end%>

                    <span><%= article.get_upvotes.size%></span>
              </div>
            </div>
    <% end%>
  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brandz</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <%flash.each do |name,msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <%end%>
        <%= yield %>
    </div>

  </body>
</html>